# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the even-valued terms.

def even_value_fibonacci(max_value):
    even_list = [2]
    i = 0
    while i < max_value:
        a = 1
        b = 2
        i = a+b
        a = b
        b = i
        if i % 2 == 0:
            even_list.append(i)
    return even_list

print(even_value_fibonacci(15))