# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with $1$ and $2$, the first $10$ terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def even_fibonacci(max_value):
    a = 1
    b = 2
    value = 0
    lst = [2]
    while value < max_value:
        value = a+b
        a = b
        b = value
        if value%2 == 0:
            lst.append(value)
    return sum(lst)

print(even_fibonacci(4000000))

